name: build tmate static binary arm64v8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm  # ubuntu arm para compilar binarios arm*
    #strategy:
      #matrix:
        #platform: [arm64v8]  # ñara AArch64 o ARM64 puedes usar `arm64v8`

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build with Docker image for ARM64
      run: |
        sudo chown -R $USER: /var/lib/gems /usr/local/bin
        bash build_static_release.sh
        ls -l

    - name: Upload releases as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: releases
        path: ./releases
