name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64]  # Para AArch64 o ARM64 puedes usar `arm64v8`, cambia si es necesario

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v2

    - name: Build the Docker image for ARM64
      run: |
        #docker buildx create --use
        #docker buildx build --platform linux/arm64 -t tmate-image .
        sudo chown -R $USER: /var/lib/gems /usr/local/bin
        bash build_static_release.sh
        ls -l

    #- name: Run Docker container to generate release
   #   run: |
    #    docker run --name tmate-build -d tmate-image
    #    docker cp tmate-build:/build/releases ./releases
    #    docker stop tmate-build
     #   docker rm tmate-build

    - name: Upload releases as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: releases
        path: ./releases
